### PR TITLE
[IDE] solve issue#12

### PR DESCRIPTION
**Pull request by aethaniel**
This patch seems to solve issue https://github.com/aethaniel/ExperimentalCore-sam/issues/12 but not only.
The issue 12 real problem was quotes not at the right place in the command line and also the missing path for libraries.

@logos-electromechanical, I have been able to compile various examples from IDE using this patch.
Do you confirm?

### CODE REVIEW

**Comment by logos-electromechanical** [comment]
@aethaniel Yes, this works, with two other very minor changes:
-- #if 0'd out USB calls in core_main.cpp
-- #if 0'd out contents of CoreUSART.c

I've got them ready to go in branch 'test' in my repository.

**Comment by aethaniel** [comment]
my fault, I did add by mistake the CoreUSART.cpp!
USB calls should be deactivated by the updated files from this PR

**Comment by aethaniel** [comment]
I just removed useless CoreUSART.cpp.
Are you sure you need to #if 0'd the USBCON #if block in main.cpp?

**Comment by logos-electromechanical** [comment]
It was failing before, but removing CoreUSART.c appeared to have cured everything. This works.

**Pull request merged**
